ARG ARCH={{ host_arch }}
FROM lopsided/archlinux:devel

# Install deps and clear pacman cache
RUN \
  pacman -Syu --noconfirm distcc which; \
  pacman -Sc --noconfirm || true;

{% for compiler_arch in host_arch|compiler_archs %}
{% if compiler_arch != host_arch %}
# Download pre-built {{ compiler_arch|toolchain }} toolchain binaries for {{ host_arch }}
ADD {{ distro.get_toolchain_url(host_arch, compiler_arch) }} /usr/lib/gcc-cross/
{% endif %}
{% endfor %}
COPY scripts/setup.sh scripts/test-arch.sh scripts/functions.sh /scripts/
COPY scripts/run-{{ host_arch|arch_slug }}.sh /scripts/run.sh

RUN \
  chmod +x /scripts/* && \
  /scripts/test-arch.sh {{ host_arch }} && rm /scripts/test-arch.sh && \
  /scripts/setup.sh && rm /scripts/setup.sh

{% if host_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

CMD /scripts/run.sh
