ARG ARCH={{ compiler_arch }}
FROM {{ distro.name }}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y \
    build-essential g++ distcc ccache && \
  apt-get clean

RUN \
  mkdir -p /scripts && \
  mkdir -p /root/.ccache

COPY scripts/* /scripts/
COPY root/.ccache /root/

# Use ccache wrappers first, distcc wrappers second
ENV PATH=/usr/lib/ccache:/usr/lib/distcc:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# If set to 0, compilation will fail when distccd can't be reached
ENV DISTCC_FALLBACK=0

# Connect to distccd on default docker network
ENV DISTCC_HOSTS=172.17.0.1:{{ compiler_arch|compiler_port }}

{% if compiler_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

RUN \
  chmod +x /scripts/* && \
  /scripts/setup.sh && \
  /scripts/test-arch.sh {{ compiler_arch }} && \
  /scripts/build-cjson.sh && \
  rm -Rf /scripts/*
