ARG ARCH={{ compiler_arch }}
FROM {{ distro.name }}

# Install deps
RUN \
  apk add --no-cache distcc ccache gcc g++ make

RUN \
  mkdir -p /scripts && \
  mkdir -p /root/.ccache

COPY scripts/* /scripts/
COPY root/.ccache/* /root/.ccache/

# Use ccache wrappers first, distcc wrappers second
ENV PATH=/usr/lib/ccache/bin:/usr/lib/distcc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# If distccd can't be reached, fail
ENV DISTCC_FALLBACK=0

# Connect to distccd on default docker network
ENV DISTCC_HOSTS=172.17.0.1:{{ host_arch|compiler_port }}

RUN \
  chmod +x /scripts/* && \
  /scripts/setup.sh && \
  /scripts/test-arch.sh {{ compiler_arch }} && \
  /scripts/build-cjson.sh && \
  rm -Rf /scripts/*
