ARG ARCH={{ compiler_arch }}
FROM {{ distro.name }}

COPY scripts/* /scripts/
COPY root/.ccache/* /root/.ccache/

# Install deps
RUN \
  chmod +x /scripts/* && \
  apk add --no-cache build-base distcc ccache{% if compiler_arch == "386" %} util-linux {% endif %}

# Use ccache wrappers first, distcc wrappers second
ENV PATH=/usr/lib/ccache/bin:/usr/lib/distcc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# If distccd can't be reached, fail
ENV DISTCC_FALLBACK=0

# Connect to distccd on default docker network
ENV DISTCC_HOSTS=172.17.0.1:{{ host_arch|compiler_port }}

{% if compiler_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

RUN \
  /scripts/setup.sh && \
  /scripts/test-arch.sh {{ compiler_arch }} && \
  /scripts/build-cjson.sh && \
  rm -Rf /scripts/*
