ARG ARCH={{ compiler_arch }}
FROM {{ distro.from_image(compiler_arch) }}

# Install deps
RUN \
  apk add --no-cache build-base distcc {% if compiler_arch == "386" %} util-linux {% endif %}

# Use distcc wrappers first
ENV PATH=/usr/lib/distcc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# If distccd can't be reached, fail
ENV DISTCC_FALLBACK=0

# Connect to distccd on default docker network
ENV DISTCC_HOSTS=172.17.0.1:{{ compiler_arch|compiler_port }}

{% if compiler_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

COPY scripts/* /scripts/

RUN \
  chmod +x /scripts/* && \
  /scripts/setup.sh && rm /scripts/setup.sh && \
  /scripts/test-arch.sh {{ compiler_arch }} && rm /scripts/test-arch.sh
