ARG ARCH={{ host_arch }}
FROM {{ distro.name }}

WORKDIR /root

# Copy test, setup, and run scripts
COPY scripts /scripts/

# Install deps for building
RUN \
  chmod +x /scripts/* && \
  apk add --no-cache build-base distcc {% if host_arch == "386" %} util-linux {% endif %}

{% for compiler_arch in host_arch|compiler_archs %}
{% if compiler_arch != host_arch %}
# Download {{ compiler_arch|toolchain }} toolchain binaries for {{ host_arch }}
ADD {{ distro.get_toolchain_url(host_arch, compiler_arch) }} /root/x-tools/
{% endif %}
{% endfor %}

{% if host_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

RUN \
  /scripts/test-arch.sh {{ host_arch }} && \
  /scripts/setup.sh
