ARG ARCH={{ host_arch }}
FROM {{ distro.name }}

WORKDIR /root

# Install deps for building
RUN \
  apk add --no-cache build-base distcc {% if host_arch == "386" %} util-linux {% endif %}

{% for compiler_arch in host_arch|compiler_archs %}
{% if compiler_arch != host_arch %}
# Download pre-built {{ compiler_arch|toolchain }} toolchain binaries for {{ host_arch }}
ADD {{ distro.get_toolchain_url(host_arch, compiler_arch) }} /root/x-tools/
{% endif %}
{% endfor %}

COPY scripts/setup.sh scripts/test-arch.sh /scripts/
COPY scripts/run-{{ host_arch }}.sh /scripts/run.sh

RUN \
  chmod +x /scripts/* && \
  /scripts/setup.sh && rm /scripts/setup.sh && \
  /scripts/test-arch.sh {{ host_arch }} && rm /scripts/test-arch.sh

{% if host_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

CMD /scripts/run.sh
