version: '3'
services:
  distcc-cross-compiler-host:
    image: elijahru/distcc-cross-compiler-host-{host_distro_slug}:latest-{host_arch}
    ports:
      # i386
      - 3603:3603
      # amd64
      - 3604:3604
      # arm32v7
      - 3607:3607
      # arm64v8
      - 3608:3608
      # s390x
      - 3609:3609
      # ppc64le
      - 3610:3610

  distcc-cross-compiler-client:
    image: elijahru/distcc-cross-compiler-client-{client_distro_slug}:latest-{client_arch}
    volumes:
      - ..:/code
    command: /code/scripts/build-cjson.sh
