version: '3'
services:
  distcc-cross-compiler-host:
    image: elijahru/distcc-cross-compiler-host-{host_distro_slug}:latest-{host_arch}
    ports:
      # amd64
      - 3704:3704
      # arm32v5
      - 3705:3705
      # arm32v6
      - 3706:3706
      # arm32v7
      - 3707:3707
      # arm64v8
      - 3708:3708

  distcc-cross-compiler-client:
    image: elijahru/distcc-cross-compiler-client-{client_distro_slug}:latest-{client_arch}
    volumes:
      - ..:/code
    command: /code/scripts/build-cjson.sh
