FROM {host_image}

# Install deps
RUN pacman -Syu --noconfirm distcc base-devel

# Clear pacman cache
RUN pacman -Sc --noconfirm

WORKDIR /root

# Install pre-built cross-compiler toolchains, as per https://archlinuxarm.org/wiki/Distcc_Cross-Compiling

# ARMv5te soft-float
COPY ./assets/distcc-cross-compiler-host-archlinux/x-tools.tar.xz x-tools.tar.xz

# ARMv6l hard-float
COPY ./assets/distcc-cross-compiler-host-archlinux/x-tools6h.tar.xz x-tools6h.tar.xz

# ARMv7l hard-float
COPY ./assets/distcc-cross-compiler-host-archlinux/x-tools7h.tar.xz x-tools7h.tar.xz

# ARMv8
COPY ./assets/distcc-cross-compiler-host-archlinux/x-tools8.tar.xz x-tools8.tar.xz

COPY ./scripts/distcc-cross-compiler-host-archlinux/setup.sh setup.sh

RUN chmod +x setup.sh && ./setup.sh

COPY ./rendered/distcc-cross-compiler-host-archlinux/etc/conf.d/* /etc/conf.d/
COPY ./rendered/distcc-cross-compiler-host-archlinux/usr/lib/systemd/system/* /usr/lib/systemd/system/
