version: '3'
services:
  distcc-cross-compiler-host:
    image: elijahru/distcc-cross-compiler-host-{host_distro_slug}:latest-{host_arch}
    ports:
      # i686-linux-gnu
      - 3603:3603
      # x86_64-linux-gnu
      - 3604:3604
      # arm-linux-gnueabihf
      - 3607:3607
      # aarch64-linux-gnu
      - 3608:3608
      # s390x-linux-gnux
      - 3609:3609
      # powerpc64le-linux-gnu
      - 3610:3610

  distcc-cross-compiler-client:
    image: elijahru/distcc-cross-compiler-client-{client_distro_slug}:latest-{client_arch}
    volumes:
      - ..:/code
    command: /code/scripts/build-cjson.sh
