FROM {host_arch}/{host_distro}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update; \
  apt-get install -y \
    build-essential g++ distcc \
    gcc-i686-linux-gnu g++-i686-linux-gnu binutils-i686-linux-gnu \
    gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf binutils-arm-linux-gnueabihf \
    gcc-aarch64-linux-gnu g++-aarch64-linux-gnu binutils-aarch64-linux-gnu \
    gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu binutils-powerpc64le-linux-gnu \
    gcc-s390x-linux-gnu g++-s390x-linux-gnu binutils-s390x-linux-gnu; \
  apt-get clean

WORKDIR /root

COPY ./rendered/distcc-cross-compiler-host-debian/etc/default/distccd-aarch64-linux-gnu /etc/default/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/default/distccd-arm-linux-gnueabihf /etc/default/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/default/distccd-i686-linux-gnu /etc/default/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/default/distccd-powerpc64le-linux-gnu /etc/default/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/default/distccd-s390x-linux-gnu /etc/default/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/default/distccd-x86_64-linux-gnu /etc/default/

COPY ./rendered/distcc-cross-compiler-host-debian/etc/init.d/distccd-aarch64-linux-gnu /etc/init.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/init.d/distccd-arm-linux-gnueabihf /etc/init.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/init.d/distccd-i686-linux-gnu /etc/init.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/init.d/distccd-powerpc64le-linux-gnu /etc/init.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/init.d/distccd-s390x-linux-gnu /etc/init.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/init.d/distccd-x86_64-linux-gnu /etc/init.d/

COPY ./rendered/distcc-cross-compiler-host-debian/etc/logrotate.d/distccd-aarch64-linux-gnu /etc/logrotate.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/logrotate.d/distccd-arm-linux-gnueabihf /etc/logrotate.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/logrotate.d/distccd-i686-linux-gnu /etc/logrotate.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/logrotate.d/distccd-powerpc64le-linux-gnu /etc/logrotate.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/logrotate.d/distccd-s390x-linux-gnu /etc/logrotate.d/
COPY ./rendered/distcc-cross-compiler-host-debian/etc/logrotate.d/distccd-x86_64-linux-gnu /etc/logrotate.d/

COPY ./scripts/distcc-cross-compiler-host-debian/setup.sh setup.sh
COPY ./scripts/distcc-cross-compiler-host-debian/run.sh run.sh

RUN \
  chmod +x /etc/init.d/distccd-* && \
  chmod +x setup.sh && \
  chmod +x run.sh && \
  ./setup.sh

CMD ./run.sh
