FROM {{ compiler_arch|image }}

# Install deps and clear pacman cache
RUN \
  pacman -Syu --noconfirm distcc ccache; \
  pacman -Sc --noconfirm || true;

RUN \
  mkdir -p /scripts && \
  mkdir -p /root/.ccache

COPY scripts/* /scripts/
COPY root/.ccache/* /root/.ccache/

RUN \
    chmod +x /scripts/* && \
    /scripts/setup.sh

# Use ccache wrappers first, distcc wrappers second
ENV PATH=/usr/lib/ccache/bin:/usr/lib/distcc/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

# If distccd can't be reached, fail
ENV DISTCC_FALLBACK=0

# Connect to distccd on default docker network
ENV DISTCC_HOSTS=172.17.0.1:{{ host_arch|compiler_port }}
