ARG ARCH={{ compiler_arch }}
FROM lopsided/archlinux:devel

# Install deps and clear pacman cache
RUN \
  pacman -Syu --noconfirm distcc ccache; \
  pacman -Sc --noconfirm || true;

RUN \
  mkdir -p /scripts && \
  mkdir -p /root/.ccache

COPY scripts/* /scripts/
COPY root/.ccache/* /root/.ccache/

# Use ccache wrappers first, distcc wrappers second
ENV PATH=/usr/lib/ccache/bin:/usr/lib/distcc/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

# If distccd can't be reached, fail
ENV DISTCC_FALLBACK=0

# Connect to distccd on default docker network
ENV DISTCC_HOSTS=172.17.0.1:{{ host_arch|compiler_port }}

{% if compiler_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

RUN \
  chmod +x /scripts/* && \
  /scripts/setup.sh && \
  /scripts/test-arch.sh {{ compiler_arch }} && \
  /scripts/build-cjson.sh && \
  rm -Rf /scripts/*
