ARG ARCH={{ host_arch }}
FROM {{ distro.name }}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update; \
  apt-get install -y \
    {{ host_arch|apt_pkgs }}; \
  apt-get clean

COPY scripts/setup.sh scripts/test-arch.sh /scripts/
COPY scripts/run-{{ host_arch|arch_slug }}.sh /scripts/run.sh

RUN \
  chmod +x /scripts/* && \
  /scripts/setup.sh && rm /scripts/setup.sh && \
  /scripts/test-arch.sh {{ host_arch }} && rm /scripts/test-arch.sh

{% if host_arch == "386" %}
# Ensure 386 container is correctly detected on x64 docker host
ENTRYPOINT ["setarch", "i686"]
{% endif %}

CMD /scripts/run.sh
