# Rendered from .github/workflows/build.yml.jinja

name: archlinux

on:
  push:
    branches: ['*']
    tags: ['*']

jobs:
  build-host-amd64:
    name: |
      host: amd64
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build host image
      run: |
        ./builder.py build-host \
          --distro archlinux \
          --host-arch amd64 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-host-arm/v5:
    name: |
      host: arm/v5
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build host image
      run: |
        ./builder.py build-host \
          --distro archlinux \
          --host-arch arm/v5 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-host-arm/v6:
    name: |
      host: arm/v6
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build host image
      run: |
        ./builder.py build-host \
          --distro archlinux \
          --host-arch arm/v6 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-host-arm/v7:
    name: |
      host: arm/v7
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build host image
      run: |
        ./builder.py build-host \
          --distro archlinux \
          --host-arch arm/v7 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-host-arm64/v8:
    name: |
      host: arm64/v8
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build host image
      run: |
        ./builder.py build-host \
          --distro archlinux \
          --host-arch arm64/v8 \
          --version $(basename ${{ github.event.ref }}) \
          --push



  build-client-amd64:
    name: |
      client: amd64

    runs-on: ubuntu-latest
    needs:
    - build-host-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build client image
      run: |
        ./builder.py build-client \
          --distro archlinux \
          --client-arch amd64 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-client-arm/v5:
    name: |
      client: arm/v5

    runs-on: ubuntu-latest
    needs:
    - build-host-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build client image
      run: |
        ./builder.py build-client \
          --distro archlinux \
          --client-arch arm/v5 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-client-arm/v6:
    name: |
      client: arm/v6

    runs-on: ubuntu-latest
    needs:
    - build-host-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build client image
      run: |
        ./builder.py build-client \
          --distro archlinux \
          --client-arch arm/v6 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-client-arm/v7:
    name: |
      client: arm/v7

    runs-on: ubuntu-latest
    needs:
    - build-host-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build client image
      run: |
        ./builder.py build-client \
          --distro archlinux \
          --client-arch arm/v7 \
          --version $(basename ${{ github.event.ref }}) \
          --push

  build-client-arm64/v8:
    name: |
      client: arm64/v8

    runs-on: ubuntu-latest
    needs:
    - build-host-amd64

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure QEMU
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y qemu qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Build client image
      run: |
        ./builder.py build-client \
          --distro archlinux \
          --client-arch arm64/v8 \
          --version $(basename ${{ github.event.ref }}) \
          --push


  push_manifests:
    name: Push manifests
    if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
      }}

    runs-on: ubuntu-latest
    needs:
    - build-host-amd64

    - build-host-arm/v5

    - build-host-arm/v6

    - build-host-arm/v7

    - build-host-arm64/v8


    - build-client-amd64

    - build-client-arm/v5

    - build-client-arm/v6

    - build-client-arm/v7

    - build-client-arm64/v8


    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Push host manifest
      run: |
        ./builder.py push-host-manifest \
          --distro archlinux \
          --version $(basename ${{ github.event.ref }})

    - name: Push client manifest
      run: |
        ./builder.py push-client-manifest \
          --distro archlinux \
          --version $(basename ${{ github.event.ref }})

  tag_latest:
    name: Tag latest
    if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
      }}

    runs-on: ubuntu-latest
    needs:
    - push_manifests

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install apt requirements
      run: |
        sudo apt-get update -q -y
        sudo apt-get -qq install -y python3-setuptools

    - name: Install pip requirements
      run: |
        pip3 install -r requirements.txt

    - name: Enable Docker experimental features
      run: |
        echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker version -f '{{.Server.Experimental}}'

    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login \
          -u elijahru --password-stdin

    - name: Tag host latest
      run: |
        ./builder.py tag-host-latest \
          --distro archlinux \
          --version $(basename ${{ github.event.ref }})

    - name: Tag client latest
      run: |-
        ./builder.py tag-client-latest \
          --distro archlinux \
          --version $(basename ${{ github.event.ref }})
